### ISSUE TITLE
calendr twig functions are not registered

### ISSUE THREAD

**Issue by bmfp** [nbehier/bolt-openagenda#2]
Hi,
I can't make the calendr helper work, calendr_* functions are not registered in twig, but oa_* are :
www-data@bolt:/var/www/bolt$ php ./app/nut debug:twig calendr
www-data@bolt:/var/www/bolt$ php ./app/nut debug:twig oa

Functions

 * oa_event(agendaAlias, eventId)
 * oa_nextEvents(agendaAlias)

service-providers are however registered :
www-data@bolt:/var/www/bolt$ php ./app/nut debug:service-providers | grep CalendR
| CalendR\Extension\Silex\Provider\CalendRServiceProvider         |    65 |
www-data@bolt:/var/www/bolt$ php ./app/nut debug:service-providers | grep OpenAgenda
| Bolt\Extension\Leskis\BoltOpenAgenda\BoltOpenAgendaExtension    |    64 |

am I missing something ?

BR

**Comment by lucaslcode** [comment]
I also have this issue

**Comment by lucaslcode** [comment]
I don't know much about php dev but it looks like the twig extension is [set up here](https://github.com/nbehier/bolt-openagenda/blob/aa8caea76e256e0a9cb057553bfc7b060c5ae17c/lib/yohang/CalendR/Extension/Silex/Provider/CalendRServiceProvider.php#L41). Is it possible the twig environment isn't set up when that is called?

**Comment by nbehier** [comment]
Hi @lucaslcode and @bmfp , unfortunately I don't have time at present to check this extension :-(
I never tested it with new bolt version… and v3.4 seems to have change _extension_ to _bundle_ and I imagine that broke down at that time… Hope I will find time in august to check that.

**Comment by nbehier** [comment]
Fix with [Release 1.1](https://github.com/nbehier/bolt-openagenda/releases/tag/v1.1)
